### PR TITLE
query grammer compileLock - ignore

### PR DESCRIPTION
**Pull request by matthewjumpsoffbuildings**
While its true spanner doesnt support explicit locking, I think the compileLock method should not throw an exception. It may be better to log a warning perhaps, but since spanner has complex lock handling and consistency, just gracefully allowing the lock to generate no additional code seems acceptable.

When using spanner with other frameworks (Laravel Nova in this case), it is necessary to ignore this.

Also if you look at: 
https://github.com/laravel/framework/blob/7907bfb50165b3951403e2d9882b4f8e0ee26b9e/src/Illuminate/Database/Query/Grammars/SQLiteGrammar.php#L29

and:
https://github.com/laravel/framework/blob/7907bfb50165b3951403e2d9882b4f8e0ee26b9e/src/Illuminate/Database/Query/Grammars/SqlServerGrammar.php#L340

You will see both of those return empty strings - I think graceful failure here is the much better approach

### CODE REVIEW

**Comment by taka-oyama** [comment]
Please add tests for this as well.

**Comment by taka-oyama** [comment]
I think fixing the ones that are failing should be enough for this case.

**Comment by matthewjumpsoffbuildings** [comment]
I see the 3 tests in BuilderTest.php, test_lock, test_lockForUpdate, test_sharedLock. Currently they depend on an exception being thrown, given the compileLock is now just returning an empty string what is the expected result?

**Comment by taka-oyama** [comment]
Please change it so that `toSql()` produces the expected query.

**Comment by matthewjumpsoffbuildings** [comment]
So drop those 3  test_lock, test_lockForUpdate, test_sharedLock methods in BuilderTest.php and just add to the test_toRawSql method?

**Comment by matthewjumpsoffbuildings** [comment]
updated the 3 lock unit test methods

**Review by taka-oyama — APPROVED** [review]

**Comment by taka-oyama** [comment]
Thanks.

**Pull request merged**
