### PR TITLE
add functionality to pass spanner types to insert/update

### PR DESCRIPTION
**Pull request by matthewjumpsoffbuildings**
This is a first attempt to resolve https://github.com/colopl/laravel-spanner/issues/149

The first step is to add a `$types` array to both Models and Builders, and to automatically inject a Models types array into every new Builder instance for that model.

The next step is overriding the base update/insert methods of the Builder, to loop through each value being passed in, and using a function `checkForType()` that attempts to apply the same conventions as the Parameterizer class, to generate an array of bound types eg `['p2' => Database::TYPE, ...]`.

The final step is adding an additional optional `$types = []` argument to Connection `update` / `insert` / `statement` / `affectingStatement` methods, so that it can be passed to the `$transaction->executeUpdate()` as an additional `types` argument alongside `parameters`

I am still not super familiar with how all the internals work here, likely there are several improvements that could be made, but hopefully this is a good jumping off point

### CODE REVIEW

**Comment by matthewjumpsoffbuildings** [comment]
Theres some issues with the types of some of the methods coming up in the unit tests, hopefully if the general ideas of this PR work, you dont mind sorting those, im not quite sure how to resolve them

**Comment by taka-oyama** [comment]
I was looking through the underlying implementation and it looks like it would be easier if you implement a `Json` class which implements [ValueInterface](https://github.com/googleapis/google-cloud-php/blob/e04603e163e33578cec39a056017afc4f2e91588/Spanner/src/ValueInterface.php) and pass that as binging.

Coversion takes place [here](https://github.com/googleapis/google-cloud-php/blob/e04603e163e33578cec39a056017afc4f2e91588/Spanner/src/ValueMapper.php#L738-L746).

**Comment by matthewjumpsoffbuildings** [comment]
Right so perhaps I could create a custom Cast class that uses the ValueInterface? That would be much simpler, this was a very hacky attempt

**Comment by matthewjumpsoffbuildings** [comment]
Though I notice this in the comments:
```
* Note: This interface may become internal in the next major version change
```
Which may be concerning?

**Comment by taka-oyama** [comment]
In that case I think it's best to throw a PR to them to add a JSON type so it's handled internally.
Seems like they already have one for [PgJsonb](https://github.com/googleapis/google-cloud-php/blob/e04603e163e33578cec39a056017afc4f2e91588/Spanner/src/PgJsonb.php).

**Comment by matthewjumpsoffbuildings** [comment]
Just checking, do I use these google type interfaces anyway? Am I on the right track to assume its via Casts?

Also I need JSON working yesterday haha, I am not sure how long a PR will take with google

**Comment by matthewjumpsoffbuildings** [comment]
Are you familiar with the ValueMapper class? Apparently this is a thing:
```php
$jsonValue = new PgJsonb('{"key": "value"}');

$valueMapper = new ValueMapper($db, true);

$mappedValue = $valueMapper->encode($jsonValue);

$result = $db->execute('INSERT INTO MyTable (JsonColumn) VALUES (@jsonValue)', [
   'parameters' => [
       'jsonValue' => $mappedValue
   ]
]);
```

**Comment by taka-oyama** [comment]
> Just checking, how do I use these google type interfaces anyway? Am I on the right track to assume its via Casts?

I had to do this for Numeric types. You will have to convert to a ValueInterface when inserting/updating by overriding [Model::getDirtryForUpdate()](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L2046) and [Model::getAttributesForInsert](https://github.com/laravel/framework/blob/0d5072b9ebb4f1de2be73f28e548b7271c75733c/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1803).

**Comment by matthewjumpsoffbuildings** [comment]
Holy moly i figured it out and its even easier - no changes required to your code at all.

If I make a custom cast like so:

```php
namespace App\Casts;

use Illuminate\Contracts\Database\Eloquent\CastsAttributes;
use Google\Cloud\Spanner\PgJsonb;
use Google\Cloud\Spanner\V1\TypeAnnotationCode;

class SpannerJsonCast implements CastsAttributes
{
	public function get($model, $key, $value, $attributes)
	{
		return json_decode($attributes[$key], true);
	}

	public function set($model, $key, $value, $attributes)
	{
		return [$key => new SpannerJsonValue($value)];
	}
}

// Just copy the PgJsonb ValueInterface class
class SpannerJsonValue extends PgJsonb
{
	// override the PgJsonb classes typeAnnotation TypeAnnotationCode::PG_JSONB
	public function typeAnnotation()
	{
		return TypeAnnotationCode::TYPE_ANNOTATION_CODE_UNSPECIFIED;
	}
}
```

Then in my model I use that cast like so:

```php
	protected $casts = [
		'ColumnName' => SpannerJsonCast::class,
	];
```

**Comment by taka-oyama** [comment]
> it throws an error from spanner saying it cant write strings to int columns

Doesn't happen to me. 
If you pass a form input, which is a string, this will happen. You have to cast it to an int first.

>  I am wondering where the implementation for your Numeric type solution is? Or has it not been released?

This is not released to public because it's not a very clean solution.

**Comment by matthewjumpsoffbuildings** [comment]
> Doesn't happen to me. If you pass a form input, which is a string, this will happen. You have to cast it to an int first like `$model->number = (int) $value`.

I am using an Eloquent model, with `$casts = [ 'column' => 'int']`, and the form is actually a Laravel Nova form, using a Number field. None of this works, always seem to get the 'cannot insert string into int64' error from spanner. The only thing that did work was making a custom cast class that uses an extension of the Numeric value type

**Comment by taka-oyama** [comment]
Then just override [Model::getDirtryForUpdate](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L2046) and [Model::getAttributesForInsert](https://github.com/laravel/framework/blob/0d5072b9ebb4f1de2be73f28e548b7271c75733c/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1803) and cast it to an int.

**Comment by taka-oyama** [comment]
Also please provide as much context as possible so we don't have to go back and forth.

**Comment by taka-oyama** [comment]
Custom type casting will be improved once google implements https://github.com/googleapis/google-cloud-php/issues/5838. Closing this for now.

**Pull request closed without merging**
